const countries = [
  { key: 'ae', value: 'AED', flag: 'ae', text: 'United Arab Emirates' },
  { key: 'af', value: 'AFN', flag: 'af', text: 'Afghanistan' },
  { key: 'al', value: 'ALL', flag: 'al', text: 'Albania' },
  { key: 'dz', value: 'DZD', flag: 'dz', text: 'Algeria' },
  { key: 'ao', value: 'AOA', flag: 'ao', text: 'Angola' },
  { key: 'ar', value: 'ARS', flag: 'ar', text: 'Argentina' },
  { key: 'aw', value: 'AWG', flag: 'aw', text: 'Aruba' },
  { key: 'ai', value: 'XCD', flag: 'ai', text: 'Anguilla' },
  { key: 'ax', value: 'EUR', flag: 'ax', text: 'Aland Islands' },
  { key: 'as', value: 'USD', flag: 'as', text: 'American Samoa' },
  { key: 'ad', value: 'EUR', flag: 'ad', text: 'Andorra' },
  { key: 'ag', value: 'XCD', flag: 'ag', text: 'Antigua' },
  { key: 'am', value: 'AMD', flag: 'am', text: 'Armenia' },
  { key: 'au', value: 'AUD', flag: 'au', text: 'Australia' },
  { key: 'at', value: 'EUR', flag: 'at', text: 'Austria' },
  { key: 'az', value: 'AZN', flag: 'az', text: 'Azerbaijan' },
  { key: 'bs', value: 'BSD', flag: 'bs', text: 'Bahamas' },
  { key: 'bh', value: 'BHD', flag: 'bh', text: 'Bahrain' },
  { key: 'bd', value: 'BDT', flag: 'bd', text: 'Bangladesh' },
  { key: 'bb', value: 'BBD', flag: 'bb', text: 'Barbados' },
  { key: 'by', value: 'BYB', flag: 'by', text: 'Belarus' },
  { key: 'be', value: 'EUR', flag: 'be', text: 'Belgium' },
  { key: 'bz', value: 'BZD', flag: 'bz', text: 'Belize' },
  { key: 'bj', value: 'XOF', flag: 'bj', text: 'Benin' },
  { key: 'bm', value: 'BMD', flag: 'bm', text: 'Bermuda' },
  { key: 'bt', value: 'BTN', flag: 'bt', text: 'Bhutan' },
  { key: 'bo', value: 'BOB', flag: 'bo', text: 'Bolivia' },
  { key: 'ba', value: 'BAM', flag: 'ba', text: 'Bosnia' },
  { key: 'bw', value: 'BWP', flag: 'bw', text: 'Botswana' },
  { key: 'br', value: 'BRL', flag: 'br', text: 'Brazil' },
  { key: 'bn', value: 'BND', flag: 'bn', text: 'Brunei' },
  { key: 'bg', value: 'BGN', flag: 'bg', text: 'Bulgaria' },
  { key: 'bf', value: 'XOF', flag: 'bf', text: 'Burkina Faso' },
  { key: 'bi', value: 'BIF', flag: 'bi', text: 'Burundi' },
  { key: 'kh', value: 'KHR', flag: 'kh', text: 'Cambodia' },
  { key: 'cm', value: 'XAF', flag: 'cm', text: 'Cameroon' },
  { key: 'ca', value: 'CAD', flag: 'ca', text: 'Canada' },
  { key: 'cv', value: 'CVE', flag: 'cv', text: 'Cape Verde' },
  { key: 'cf', value: 'XAF', flag: 'cf', text: 'Central African Republic' },
  { key: 'td', value: 'XAF', flag: 'td', text: 'Chad' },
  { key: 'cl', value: 'CLP', flag: 'cl', text: 'Chile' },
  { key: 'cn', value: 'CNY', flag: 'cn', text: 'China' },
  { key: 'co', value: 'COP', flag: 'co', text: 'Colombia' },
  { key: 'km', value: 'KMF', flag: 'km', text: 'Comoros' },
  { key: 'cg', value: 'XAF', flag: 'cg', text: 'Congo Brazzaville' },
  { key: 'cd', value: 'CDF', flag: 'cd', text: 'Congo' },
  { key: 'cr', value: 'CRC', flag: 'cr', text: 'Costa Rica' },
  { key: 'ci', value: 'XOF', flag: 'ci', text: "Cote d'Ivoire" },
  { key: 'hr', value: 'HRK', flag: 'hr', text: 'Croatia' },
  { key: 'cu', value: 'CUC', flag: 'cu', text: 'Cuba' },
  { key: 'cy', value: 'CYP', flag: 'cy', text: 'Cyprus' },
  { key: 'cz', value: 'CZK', flag: 'cz', text: 'Czech Republic' },
  { key: 'dk', value: 'DKK', flag: 'dk', text: 'Denmark' },
  { key: 'dj', value: 'DJF', flag: 'dj', text: 'Djibouti' },
  { key: 'dm', value: 'XCD', flag: 'dm', text: 'Dominica' },
  { key: 'do', value: 'DOP', flag: 'do', text: 'Dominican Republic' },
  { key: 'ec', value: 'USD', flag: 'ec', text: 'Ecuador' },
  { key: 'eg', value: 'EGP', flag: 'eg', text: 'Egypt' },
  { key: 'sv', value: 'USD', flag: 'sv', text: 'El Salvador' },
  { key: 'gq', value: 'XAF', flag: 'gq', text: 'Equatorial Guinea' },
  { key: 'er', value: 'ERN', flag: 'er', text: 'Eritrea' },
  { key: 'ee', value: 'EUR', flag: 'ee', text: 'Estonia' },
  { key: 'et', value: 'ETB', flag: 'et', text: 'Ethiopia' },
  { key: 'fk', value: 'FKP', flag: 'fk', text: 'Falkland Islands' },
  { key: 'fo', value: 'DKK', flag: 'fo', text: 'Faroe Islands' },
  { key: 'fj', value: 'FJD', flag: 'fj', text: 'Fiji' },
  { key: 'fi', value: 'EUR', flag: 'fi', text: 'Finland' },
  { key: 'fr', value: 'EUR', flag: 'fr', text: 'France' },
  { key: 'gf', value: 'EUR', flag: 'gf', text: 'French Guiana' },
  { key: 'pf', value: 'XPF', flag: 'pf', text: 'French Polynesia' },
  { key: 'ga', value: 'XAF', flag: 'ga', text: 'Gabon' },
  { key: 'gm', value: 'GMD', flag: 'gm', text: 'Gambia' },
  { key: 'ge', value: 'GEL', flag: 'ge', text: 'Georgia' },
  { key: 'de', value: 'EUR', flag: 'de', text: 'Germany' },
  { key: 'gh', value: 'GHS', flag: 'gh', text: 'Ghana' },
  { key: 'gi', value: 'GIP', flag: 'gi', text: 'Gibraltar' },
  { key: 'gr', value: 'EUR', flag: 'gr', text: 'Greece' },
  { key: 'gl', value: 'DKK', flag: 'gl', text: 'Greenland' },
  { key: 'gd', value: 'XCD', flag: 'gd', text: 'Grenada' },
  { key: 'gp', value: 'EUR', flag: 'gp', text: 'Guadeloupe' },
  { key: 'gu', value: 'USD', flag: 'gu', text: 'Guam' },
  { key: 'gt', value: 'GTQ', flag: 'gt', text: 'Guatemala' },
  { key: 'gn', value: 'GNF', flag: 'gn', text: 'Guinea' },
  { key: 'gw', value: 'XOF', flag: 'gw', text: 'Guinea-Bissau' },
  { key: 'gy', value: 'GYD', flag: 'gy', text: 'Guyana' },
  { key: 'ht', value: 'HTG', flag: 'ht', text: 'Haiti' },
  { key: 'hn', value: 'HNL', flag: 'hn', text: 'Honduras' },
  { key: 'hk', value: 'HKD', flag: 'hk', text: 'Hong Kong' },
  { key: 'hu', value: 'HUF', flag: 'hu', text: 'Hungary' },
  { key: 'is', value: 'ISK', flag: 'is', text: 'Iceland' },
  { key: 'in', value: 'INR', flag: 'in', text: 'India' },
  { key: 'id', value: 'IDR', flag: 'id', text: 'Indonesia' },
  { key: 'ir', value: 'IRR', flag: 'ir', text: 'Iran' },
  { key: 'iq', value: 'IQD', flag: 'iq', text: 'Iraq' },
  { key: 'ie', value: 'EUR', flag: 'ie', text: 'Ireland' },
]

export default countries
